### ISSUE TITLE
3.14.33 kernel

### ISSUE THREAD

**Issue by awright424** [VegetableAvenger/BBBIOlib#12]
Do you plan on updating your library to be compatible with the latest kernel. that will include making changes to be compatible with the new way of handling device tree overlays.

**Comment by VegetableAvenger** [comment]
Sorry for my late reply.

Any signal output from PWN pins when program works ?

Maybe the PWM pins is not work in PWM mode.

you could using the EP_status to check the pinmux status .

if the pinmux status not work in PWM mode, the BBBIO-EHRPWM overlay in overlay directory is one way to change the pinmux status .
