### ISSUE TITLE
similiar functions different output

### ISSUE THREAD

**Issue by awright424** [VegetableAvenger/BBBIOlib#13]
I have some code written that works well with controlling the speed of a motor using the beaglebone blacks motocape. I have also written a more complex program that doesnt seem to work when passing the values to BBBIO_PWMSS_Setting(BBBIO_PWMSS1, 25.0f, speed, angle); function. I am not sure what I am doing wrong and any help is appreciated.

here is my original working code: http://paste.ubuntu.com/10870922/
here is the new not working code: http://paste.ubuntu.com/10870923/

**Comment by VegetableAvenger** [comment]
Hi,

Sorry for my late reply.

Any signal output from PWN pins when program works ?

Maybe the PWM pins is not work in PWM mode.

you could using the EP_status to check the pinmux status .

if the pinmux status not work in PWM mode, the BBBIO-EHRPWM overlay in overlay directory is one way to change the pinmux status .
