### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by secret-lain** [VegetableAvenger/BBBIOlib#14]
Hi i'm trying to SPI interface through BBBIO.

after iolib_init(),

i set
BBBIO_McSPI_channel_ctrl
and used function Enable - McSPI_work - Disable.

But it errored
BBBIO_McSPI_CLK_set: No effect pin mux Detected of SPI-0 ,Please use EP_STATUS toolkit to check Pin mux mode
BBBIO_McSPI_work: McSPI 0 CM_PER Clock Gating!
BBBIO_McSPI_CLK_set: No effect pin mux Detected of SPI-0 ,Please use EP_STATUS toolkit to check Pin mux mode

so i use EP_STATUS toolkit and pin mux mode is not correct for use SPI interface

any idea or function in BBBIO to change pin mux mode? or i misused that?

**Comment by awright424** [comment]
Did you load the spi overlay?

**Comment by vvvb78** [comment]
sorry i didn't. but i got another problem when i try to load BBBIO-SPI1 to slots.
i got error message
[bash: echo: write error: File exists]

i'm newbie for linux, sorry :-)

and OS on BBB is BeagleBoard.org BeagleBone Debian Image 2014-04-23.

what should i do?

and what is 'bad file descripter' error?

**Comment by VegetableAvenger** [comment]
Hi,  

These error shows about the pinmux status error.

There are some illustration in "overlay" directory to slove this problem (for kernel 3.8 ... 3.15 or newer no avail). 

	to load SPI overlay : echo BBBIO-SPI1 >> /sys/devices/bone_capemgr.*/slots

The "File exists" message is prompted, if you load one overlay twice or more.

You could check the pinmux status by EP_STATUS after overlay loaded, or check the slots by cat command .

**Comment by secret-lain** [comment]
oh i solved that
i just didn't disable HDMI pin overlay

thank you
